### ISSUE TITLE
no if statement on typingLimit

### ISSUE THREAD

**Issue by mdskinner** [calendee/val-on-timeout#1]
Hi, love the module.. but there is no if statement on typingLimit which means i don't get to control it by my form properties. It auto starts on keypress regardless.

Also noticed with typingLimit = parseInt(attrs.typingLimit, 10) || 1250
it seems that parseInt is taking to long to propagate result and passing over to your default regardless of attrs.typingLimit value.

i've updated mine locally to: 

               if( attrs.hasOwnProperty('typingLimit')) {

                 typingLimit = parseInt(attrs.typingLimit)
                 if ( !(typingLimit >=0) ) typingLimit = 500;

                 elem.bind('keydown', function() {

                     // If the field has already timedout, don't change it.
                     if(ctrl.$timedout) return;

                     // If timer is already running, kill it
                     if(timer) cancelTimer();

                     // Start the timer
                     startTimer(typingLimit);

                 });
               }

it seems to be more stable. it would be great to have something like this reflected in the repo on all files (including .min.js)

i would have done something like  if ( typeof typingLimit != 'number' ) ) typingLimit = 500;
but typeof NaN is equal to 'number'  :)

**Comment by calendee** [comment]
@mdskinner Thanks for the input.  To be honest, I've sort of abandoned this.  With the new form improvements in AngularJS 1.3, I haven't really needed this anymore.  You might want to check them out. 

https://calendee.com/2014/12/26/validation-in-ionic-framework-apps-with-ngmessages/

If you're still interested in these changes, can you do a Pull Request?  If you do I will review and merge it.

**Comment by mdskinner** [comment]
Wow, ok, thats a nice module! With that and input.$touched && form.$submitted i have everything i need.

Thanks

**Comment by calendee** [comment]
Excellent.  The new form validation really made me like Angular again.  I'm going to close this now.
